import {
  Activity,
  PanelLeftClose,
  PanelLeftOpen,
  Maximize,
  Minimize,
  Download,
  LayoutDashboard,
  ArrowDownRight,
  Circle,
  CircleCheck,
  FileCog,
  FileText,
  FolderOpen,
  House,
  Layers3,
  LogOut,
  PanelBottomClose,
  Play,
  Plus,
  Power,
  RotateCcw,
  RotateCw,
  Save,
  Search,
  Settings2,
  Square,
  SquarePen,
  TriangleAlert,
} from "@lucide/vue";

/** 显式导入使用中的 SVG 图标，使未使用的图标不进入生产包。 */
export const icons = {
  collapse: PanelLeftClose,
  expand: PanelLeftOpen,
  fullscreen: Maximize,
  restore: Minimize,
  download: Download,
  dashboard: LayoutDashboard,
  monitor: Activity,
  config: FileCog,
  settings: Settings2,
  processes: Layers3,
  running: Activity,
  attention: TriangleAlert,
  autostart: Power,
  reload: RotateCw,
  add: Plus,
  tray: PanelBottomClose,
  edit: SquarePen,
  start: Play,
  stop: Square,
  restart: RotateCcw,
  reset: CircleCheck,
  save: Save,
  file: FileText,
  folder: FolderOpen,
  home: House,
  quit: LogOut,
  search: Search,
  arrow: ArrowDownRight,
  dirty: Circle,
  synced: CircleCheck,
} as const;

/** 界面允许使用的图标名称，避免拼写错误或动态加载整个图标库。 */
export type IconName = keyof typeof icons;
